### ISSUE TITLE
master (1ba028659c) failing to build on MacOS 10.14.6 (18G103)

### ISSUE THREAD

**Issue by jeremyBanks** [o2sh/onefetch#90]
```
$ history
[...]
  516  git clone git@github.com:o2sh/onefetch.git
  517  cd onefetch
  518  make install
```

```
   Compiling onefetch v1.6.5 (/Users/jbanks/onefetch)
error[E0425]: cannot find function `enable_ansi_support` in crate `ansi_term`
   --> src/main.rs:449:37
    |
449 |     if cfg!(windows) && !ansi_term::enable_ansi_support().is_ok() {
    |                                     ^^^^^^^^^^^^^^^^^^^ not found in `ansi_term`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `onefetch`.

To learn more, run the command again with --verbose.
make: *** [build] Error 101
```

**Comment by spenserblack** [comment]
The build is passing now. @jeremyBanks, is this still an issue?

**Comment by jeremyBanks** [comment]
@spenserblack It builds/installs/runs successfully now after pulling latest `master`, thanks!
